        CREATE SEQUENCE IF NOT EXISTS images_id_seq START 1;

        CREATE TABLE IF NOT EXISTS images (
            -- Primary key: ID auto-generated via images_id_seq sequence
            -- (DuckDB 1.2.2 silently drops GENERATED BY DEFAULT AS IDENTITY,
            -- so we use the underlying mechanism directly)
            id INTEGER PRIMARY KEY DEFAULT nextval('images_id_seq'),

            -- File system properties
            -- UNIQUE constraint on file_path prevents duplicate imports
            -- This allows INSERT OR IGNORE to silently skip duplicates during batch ingestion
            file_path TEXT NOT NULL UNIQUE,
            file_size BIGINT NOT NULL,  -- BIGINT (64-bit) required: large TIFFs and PSDs can exceed 2.1GB INT32 limit
            file_name TEXT NOT NULL,
            file_extension TEXT,
            -- Filename-derived columns for cross-directory duplicate consolidation
            -- (DESIGN-Duplicate-Consolidation.md §5). Populated at ingest by
            -- parse_filename(). Nullable in DDL — the non-null invariant is enforced
            -- at the populate-time contract (new-record ingest + one-time backfill),
            -- the same pattern as `rotation INTEGER DEFAULT 0`. file_stem preserves
            -- original case (display); image_kind is always lowercase ("jpeg" /
            -- "raw" / "other"). Comparisons that need case-folding apply LOWER() at
            -- the boundary (see Section 12, Canonical Case for String Comparisons).
            file_stem VARCHAR,
            image_kind VARCHAR,
            -- Stored parent-directory derivation for filter-aware pagination
            -- (DESIGN-Filter-Aware-Pagination.md §4). Populated at ingest from
            -- file_path via the canonical SUBSTRING/INSTR/REVERSE expression
            -- (see get_distinct_directory_paths for the canonical form, and the
            -- "Directory-Path Extraction SQL — Gotcha" note in CLAUDE.md for the
            -- alternative left-anchored form that must NOT be used). Nullable in
            -- DDL — the non-null invariant is enforced at the populate-time
            -- contract (new-record ingest + one-time backfill), same pattern as
            -- file_stem / image_kind above. Consumed by the RAW+JPEG pair-collapse
            -- subquery introduced in Session 19 Step 4.
            directory_path VARCHAR,
            created_timestamp INTEGER NOT NULL,  -- Unix epoch seconds
            modified_timestamp INTEGER NOT NULL, -- Unix epoch seconds

            -- Camera/capture metadata (nullable — not all images have complete EXIF)
            camera_make TEXT,
            camera_model TEXT,
            lens_model TEXT,
            focal_length REAL,      -- Millimeters
            aperture REAL,          -- F-stop value
            shutter_speed REAL,     -- Seconds
            iso INTEGER,            -- ISO speed rating
            capture_datetime TEXT,  -- ISO 8601 string

            -- Image properties
            pixel_width INTEGER,
            pixel_height INTEGER,
            color_space TEXT,
            bit_depth INTEGER,

            -- GPS coordinates (from geotagged images)
            gps_latitude REAL,
            gps_longitude REAL,
            gps_altitude REAL,

            -- IPTC/copyright metadata
            copyright TEXT,
            creator TEXT,
            description TEXT,

            -- Organization metadata (user-assigned)
            rating INTEGER,      -- 0-5 stars
            flag TEXT,           -- "pick", "reject", or NULL
            color_label TEXT,    -- "red", "green", "blue", etc.
            rotation INTEGER DEFAULT 0,  -- Image rotation in degrees: 0, 90, 180, or 270

            -- Audit timestamp: when this record was added to the catalogue
            indexed_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        -- Schema upgrade for pre-existing catalogues
        -- (DESIGN-Duplicate-Consolidation.md §5, decision C1 from the Step (a')
        -- read-and-confirm pass; DESIGN-Filter-Aware-Pagination.md §4 added
        -- directory_path in Session 19 Step 1). CREATE TABLE IF NOT EXISTS is a
        -- no-op when the images table already exists, so it cannot add columns
        -- to pre-existing catalogues. The ALTER TABLE ADD COLUMN IF NOT EXISTS
        -- trio below is the migration path: on a fresh database these are no-ops
        -- (the columns were just defined above); on an existing catalogue these
        -- add the columns the backfill migration then populates.
        ALTER TABLE images ADD COLUMN IF NOT EXISTS file_stem VARCHAR;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS image_kind VARCHAR;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS directory_path VARCHAR;

        -- Indexes for efficient filtering and querying
        -- These columns are commonly used in WHERE clauses and ORDER BY operations
        -- Rationale: Photographers frequently filter by camera, date, rating, and organization markers
        CREATE INDEX IF NOT EXISTS idx_camera_model ON images(camera_model);
        CREATE INDEX IF NOT EXISTS idx_capture_datetime ON images(capture_datetime);
        CREATE INDEX IF NOT EXISTS idx_created_timestamp ON images(created_timestamp);
        CREATE INDEX IF NOT EXISTS idx_file_extension ON images(file_extension);
        CREATE INDEX IF NOT EXISTS idx_rating ON images(rating);
        CREATE INDEX IF NOT EXISTS idx_flag ON images(flag);
        CREATE INDEX IF NOT EXISTS idx_color_label ON images(color_label);

        -- === Keyword system (Session 45; Docs/DESIGN-Keyword-System.md) ===
        -- Hierarchical keywords in ONE table. Each applied keyword PATH is
        -- materialized as one row per ancestor level; each row carries `label`
        -- (that node, = last path segment) and `path` (root->that node,
        -- U+001F-joined). Soft-hide via `status` (1 = active/retained, 0 =
        -- hidden); `created_at`/`hidden_at` move together. `label` is the hot
        -- query key; `path` is the structural truth. No stored `level` (it is
        -- derivable from `path`).
        CREATE SEQUENCE IF NOT EXISTS keyword_id_seq START 1;

        CREATE TABLE IF NOT EXISTS keyword (
            id INTEGER PRIMARY KEY DEFAULT nextval('keyword_id_seq'),
            image_id INTEGER NOT NULL,          -- -> images.id (the "image pointer")
            label TEXT NOT NULL,                -- this node's text (= last path segment)
            path TEXT NOT NULL,                 -- root->this node, U+001F-separated
            status INTEGER NOT NULL DEFAULT 1,  -- 1 = active, 0 = hidden (soft-delete)
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            hidden_at TIMESTAMP                 -- set when status->0; NULL while active
        );

        CREATE INDEX IF NOT EXISTS idx_keyword_image_id ON keyword(image_id);
        CREATE INDEX IF NOT EXISTS idx_keyword_label ON keyword(label);
        CREATE INDEX IF NOT EXISTS idx_keyword_path ON keyword(path);
        CREATE INDEX IF NOT EXISTS idx_keyword_status ON keyword(status);

        -- Active-only view: ALL normal keyword reads/queries hit this so the
        -- status filter can never be forgotten. Recovery reads the raw table.
        CREATE OR REPLACE VIEW keyword_visible AS
            SELECT * FROM keyword WHERE status = 1;
