        CREATE SEQUENCE IF NOT EXISTS images_id_seq START 1;

        CREATE TABLE IF NOT EXISTS images (
            -- Primary key: ID auto-generated via images_id_seq sequence
            -- (DuckDB 1.2.2 silently drops GENERATED BY DEFAULT AS IDENTITY,
            -- so we use the underlying mechanism directly)
            id INTEGER PRIMARY KEY DEFAULT nextval('images_id_seq'),

            -- File system properties
            -- UNIQUE constraint on file_path prevents duplicate imports
            -- This allows INSERT OR IGNORE to silently skip duplicates during batch ingestion
            file_path TEXT NOT NULL UNIQUE,
            file_size BIGINT NOT NULL,  -- BIGINT (64-bit) required: large TIFFs and PSDs can exceed 2.1GB INT32 limit
            file_name TEXT NOT NULL,
            file_extension TEXT,
            -- Filename-derived columns for cross-directory duplicate consolidation
            -- (DESIGN-Duplicate-Consolidation.md §5). Populated at ingest by
            -- parse_filename(). Nullable in DDL — the non-null invariant is enforced
            -- at the populate-time contract (new-record ingest + one-time backfill),
            -- the same pattern as `rotation INTEGER DEFAULT 0`. file_stem preserves
            -- original case (display); image_kind is always lowercase ("jpeg" /
            -- "raw" / "other"). Comparisons that need case-folding apply LOWER() at
            -- the boundary (see Section 12, Canonical Case for String Comparisons).
            file_stem VARCHAR,
            image_kind VARCHAR,
            -- Stored parent-directory derivation for filter-aware pagination
            -- (DESIGN-Filter-Aware-Pagination.md §4). Populated at ingest from
            -- file_path via the canonical SUBSTRING/INSTR/REVERSE expression
            -- (see get_distinct_directory_paths for the canonical form, and the
            -- "Directory-Path Extraction SQL — Gotcha" note in CLAUDE.md for the
            -- alternative left-anchored form that must NOT be used). Nullable in
            -- DDL — the non-null invariant is enforced at the populate-time
            -- contract (new-record ingest + one-time backfill), same pattern as
            -- file_stem / image_kind above. Consumed by the RAW+JPEG pair-collapse
            -- subquery introduced in Session 19 Step 4.
            directory_path VARCHAR,
            created_timestamp INTEGER NOT NULL,  -- Unix epoch seconds
            modified_timestamp INTEGER NOT NULL, -- Unix epoch seconds

            -- Camera/capture metadata (nullable — not all images have complete EXIF)
            camera_make TEXT,
            camera_model TEXT,
            lens_model TEXT,
            focal_length REAL,      -- Millimeters
            aperture REAL,          -- F-stop value
            shutter_speed REAL,     -- Seconds
            iso INTEGER,            -- ISO speed rating
            capture_datetime TEXT,  -- ISO 8601 string

            -- Image properties
            pixel_width INTEGER,
            pixel_height INTEGER,
            color_space TEXT,
            bit_depth INTEGER,

            -- GPS coordinates (from geotagged images)
            gps_latitude REAL,
            gps_longitude REAL,
            gps_altitude REAL,

            -- IPTC/copyright metadata
            copyright TEXT,
            creator TEXT,
            description TEXT,

            -- Organization metadata (user-assigned)
            rating INTEGER,      -- 0-5 stars
            flag TEXT,           -- "pick", "reject", or NULL
            color_label TEXT,    -- "red", "green", "blue", etc.
            rotation INTEGER DEFAULT 0,  -- Image rotation in degrees: 0, 90, 180, or 270

            -- === Intelligent culling / focus analysis (Session 76; Docs/DESIGN-Intelligent-Culling.md) ===
            -- Scalar machine-derived facts. User curation fields above remain
            -- untouched; focus analysis is advisory and filterable, never an
            -- automatic rating/flag/color write.
            focus_score DOUBLE,              -- Laplacian-variance score; higher = sharper
            focus_basis TEXT,                -- human_face / animal / foreground / saliency / animal_pose / whole_image / unknown
            focus_human_score DOUBLE,
            focus_animal_score DOUBLE,
            focus_foreground_score DOUBLE,
            focus_saliency_score DOUBLE,
            focus_animal_pose_score DOUBLE,
            focus_whole_image_score DOUBLE,
            focus_algorithm_version TEXT,    -- e.g. "laplacian-v1"
            focus_analysis_status TEXT,      -- complete / online_only / unreadable / failed
            focus_analysis_attempt_id TEXT,
            focus_scored_at TIMESTAMP,
            face_count INTEGER,              -- Vision-detected people count (0 = no faces detected)
            face_quality_best DOUBLE,        -- Best Apple Vision faceCaptureQuality in image
            face_quality_average DOUBLE,     -- Average faceCaptureQuality across scored faces
            face_quality_min DOUBLE,         -- Lowest faceCaptureQuality across scored faces
            face_eyes_open_count INTEGER,    -- Heuristic count of faces whose eyes appear open
            face_blink_risk_count INTEGER,   -- Heuristic count of faces with likely blink/closed eyes

            -- === Video / unified-media support (Session 70; Docs/DESIGN-Video-Schema-Unified-Table.md) ===
            -- is_video discriminates stills (FALSE) from video (TRUE). CREATE-time
            -- default is safe; the ALTER path below adds it WITHOUT a default then
            -- backfills FALSE (S62 WAL rule). Video rows leave the EXIF columns NULL
            -- and stills leave these NULL — columnar storage makes that nearly free.
            is_video BOOLEAN NOT NULL DEFAULT FALSE,

            -- Video stream (NULL for stills)
            duration_seconds DOUBLE,             -- container duration, seconds
            frame_rate DOUBLE,                   -- nominal fps (e.g. 29.97)
            video_kind TEXT,                     -- container: 'mov' / 'mp4' / 'mxf'
            video_codec TEXT,                    -- 'hevc' / 'prores' / 'h264'
            video_bitrate BIGINT,                -- bits per second

            -- Color science (CICP — applies to HDR stills too; distinct from
            -- color_space above, which is the still's ICC profile name)
            color_primaries TEXT,                -- 'bt2020' / 'smpte432' (P3) / 'bt709'
            color_transfer TEXT,                 -- 'arib-std-b67' (HLG) / 'smpte2084' (PQ) / 'bt709'
            color_matrix TEXT,                   -- 'bt2020nc' / 'smpte170m' / 'bt709'
            color_range TEXT,                    -- 'tv' (limited) / 'pc' (full)
            dv_profile INTEGER,                  -- Dolby Vision profile (8 on iPhone); NULL = none

            -- Audio stream (NULL for stills / silent video)
            has_audio BOOLEAN,
            audio_codec TEXT,                    -- 'aac' / 'pcm_s16le' / 'pcm_s24le'
            audio_channels INTEGER,              -- 1 / 2
            audio_sample_rate INTEGER,           -- 44100 / 48000
            audio_bitrate BIGINT,                -- bits per second

            -- Live Photo: QuickTime content.identifier UUID, shared by the still +
            -- motion pair. NULL = not a Live Photo. Pair = rows with equal value.
            live_photo_id TEXT,

            -- Apple Photos import provenance (Apple Photos in-place catalogue).
            -- ZASSET.ZUUID of the source asset; non-NULL marks an Apple-managed
            -- row and is the PhotoKit handle for on-demand materialize. NULL for
            -- scanned / Lightroom-imported rows.
            external_source_id TEXT,

            -- Audit timestamp: when this record was added to the catalogue
            indexed_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        -- Schema upgrade for pre-existing catalogues
        -- (DESIGN-Duplicate-Consolidation.md §5, decision C1 from the Step (a')
        -- read-and-confirm pass; DESIGN-Filter-Aware-Pagination.md §4 added
        -- directory_path in Session 19 Step 1). CREATE TABLE IF NOT EXISTS is a
        -- no-op when the images table already exists, so it cannot add columns
        -- to pre-existing catalogues. The ALTER TABLE ADD COLUMN IF NOT EXISTS
        -- trio below is the migration path: on a fresh database these are no-ops
        -- (the columns were just defined above); on an existing catalogue these
        -- add the columns the backfill migration then populates.
        ALTER TABLE images ADD COLUMN IF NOT EXISTS file_stem VARCHAR;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS image_kind VARCHAR;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS directory_path VARCHAR;

        -- Intelligent culling / focus-analysis columns (Session 76). ADD COLUMN
        -- with NO default (S62 WAL rule). Existing rows stay NULL and therefore
        -- naturally form the pending analysis queue.
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_score DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_basis TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_human_score DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_animal_score DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_foreground_score DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_saliency_score DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_animal_pose_score DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_whole_image_score DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_algorithm_version TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_analysis_status TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_analysis_attempt_id TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS focus_scored_at TIMESTAMP;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS face_count INTEGER;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS face_quality_best DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS face_quality_average DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS face_quality_min DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS face_eyes_open_count INTEGER;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS face_blink_risk_count INTEGER;

        -- Video / unified-media columns (Session 70). ADD COLUMN IF NOT EXISTS with
        -- NO default (an ALTER ... ADD COLUMN ... DEFAULT <expr> does not survive
        -- WAL replay — S62), then backfill only the is_video discriminator; the
        -- rest are correctly NULL on existing stills.
        ALTER TABLE images ADD COLUMN IF NOT EXISTS is_video BOOLEAN;
        UPDATE images SET is_video = FALSE WHERE is_video IS NULL;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS duration_seconds DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS frame_rate DOUBLE;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS video_kind TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS video_codec TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS video_bitrate BIGINT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS color_primaries TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS color_transfer TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS color_matrix TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS color_range TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS dv_profile INTEGER;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS has_audio BOOLEAN;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS audio_codec TEXT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS audio_channels INTEGER;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS audio_sample_rate INTEGER;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS audio_bitrate BIGINT;
        ALTER TABLE images ADD COLUMN IF NOT EXISTS live_photo_id TEXT;

        -- Apple Photos import provenance (Apple Photos in-place catalogue).
        -- ADD COLUMN with NO default (S62 WAL rule); existing rows stay NULL,
        -- which correctly means "not an Apple-managed asset".
        ALTER TABLE images ADD COLUMN IF NOT EXISTS external_source_id TEXT;

        -- Indexes for efficient filtering and querying
        -- These columns are commonly used in WHERE clauses and ORDER BY operations
        -- Rationale: Photographers frequently filter by camera, date, rating, and organization markers
        CREATE INDEX IF NOT EXISTS idx_camera_model ON images(camera_model);
        CREATE INDEX IF NOT EXISTS idx_capture_datetime ON images(capture_datetime);
        CREATE INDEX IF NOT EXISTS idx_created_timestamp ON images(created_timestamp);
        CREATE INDEX IF NOT EXISTS idx_file_extension ON images(file_extension);
        CREATE INDEX IF NOT EXISTS idx_rating ON images(rating);
        CREATE INDEX IF NOT EXISTS idx_flag ON images(flag);
        CREATE INDEX IF NOT EXISTS idx_color_label ON images(color_label);
        CREATE INDEX IF NOT EXISTS idx_focus_score ON images(focus_score);
        CREATE INDEX IF NOT EXISTS idx_focus_human_score ON images(focus_human_score);
        CREATE INDEX IF NOT EXISTS idx_focus_animal_score ON images(focus_animal_score);
        CREATE INDEX IF NOT EXISTS idx_focus_foreground_score ON images(focus_foreground_score);
        CREATE INDEX IF NOT EXISTS idx_focus_saliency_score ON images(focus_saliency_score);
        CREATE INDEX IF NOT EXISTS idx_focus_animal_pose_score ON images(focus_animal_pose_score);
        CREATE INDEX IF NOT EXISTS idx_focus_whole_image_score ON images(focus_whole_image_score);
        CREATE INDEX IF NOT EXISTS idx_focus_analysis_status ON images(focus_analysis_status);
        CREATE INDEX IF NOT EXISTS idx_face_count ON images(face_count);
        CREATE INDEX IF NOT EXISTS idx_face_quality_best ON images(face_quality_best);
        CREATE INDEX IF NOT EXISTS idx_face_quality_average ON images(face_quality_average);
        CREATE INDEX IF NOT EXISTS idx_face_quality_min ON images(face_quality_min);
        CREATE INDEX IF NOT EXISTS idx_face_eyes_open_count ON images(face_eyes_open_count);
        CREATE INDEX IF NOT EXISTS idx_face_blink_risk_count ON images(face_blink_risk_count);

        -- === Face observations (Vision detection, pre-recognition) ===
        -- One row per detected human face per image/algorithm version. This is
        -- the durable scalar side of face detection: geometry, capture quality,
        -- focus, eye-state measurements, and coarse alignment landmarks. Future
        -- AuraFace embeddings belong in LanceDB keyed by face_observation.id.
        CREATE SEQUENCE IF NOT EXISTS face_observation_id_seq START 1;

        CREATE TABLE IF NOT EXISTS face_observation (
            id INTEGER PRIMARY KEY DEFAULT nextval('face_observation_id_seq'),
            image_id INTEGER NOT NULL,
            analyzed_image_id INTEGER NOT NULL,
            face_index INTEGER NOT NULL,
            algorithm_version TEXT NOT NULL,
            analysis_run_id TEXT NOT NULL,
            bounding_box_x DOUBLE NOT NULL,
            bounding_box_y DOUBLE NOT NULL,
            bounding_box_width DOUBLE NOT NULL,
            bounding_box_height DOUBLE NOT NULL,
            detection_confidence DOUBLE,
            face_capture_quality DOUBLE,
            face_focus_score DOUBLE,
            left_eye_open_score DOUBLE,
            right_eye_open_score DOUBLE,
            eyes_open_score DOUBLE,
            blink_risk_score DOUBLE,
            left_eye_x DOUBLE,
            left_eye_y DOUBLE,
            right_eye_x DOUBLE,
            right_eye_y DOUBLE,
            nose_x DOUBLE,
            nose_y DOUBLE,
            mouth_left_x DOUBLE,
            mouth_left_y DOUBLE,
            mouth_right_x DOUBLE,
            mouth_right_y DOUBLE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (image_id, algorithm_version, face_index)
        );

        CREATE INDEX IF NOT EXISTS idx_face_observation_image ON face_observation(image_id);
        CREATE INDEX IF NOT EXISTS idx_face_observation_analyzed_image ON face_observation(analyzed_image_id);
        CREATE INDEX IF NOT EXISTS idx_face_observation_algorithm ON face_observation(algorithm_version);
        CREATE INDEX IF NOT EXISTS idx_face_observation_run ON face_observation(analysis_run_id);

        -- === Face recognition cluster diagnostics (developer-only first pass) ===
        -- AuraFace vectors live in LanceDB keyed by face_observation.id. These
        -- DuckDB tables persist the scalar result of one clustering run so
        -- diagnostics can prove readback before any person/naming UI exists.
        CREATE TABLE IF NOT EXISTS face_cluster_run (
            run_id TEXT PRIMARY KEY,
            face_algorithm_version TEXT NOT NULL,
            model_version TEXT NOT NULL,
            preprocessing_version TEXT NOT NULL,
            threshold DOUBLE NOT NULL,
            cluster_count INTEGER NOT NULL,
            member_count INTEGER NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS face_cluster_member (
            run_id TEXT NOT NULL,
            cluster_id INTEGER NOT NULL,
            face_observation_id INTEGER NOT NULL,
            image_id INTEGER NOT NULL,
            analyzed_image_id INTEGER NOT NULL,
            face_index INTEGER NOT NULL,
            member_rank INTEGER NOT NULL,
            cluster_size INTEGER NOT NULL,
            nearest_neighbor_face_observation_id INTEGER,
            nearest_neighbor_cosine DOUBLE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (run_id, face_observation_id)
        );

        CREATE INDEX IF NOT EXISTS idx_face_cluster_member_run ON face_cluster_member(run_id);
        CREATE INDEX IF NOT EXISTS idx_face_cluster_member_cluster ON face_cluster_member(run_id, cluster_id);
        CREATE INDEX IF NOT EXISTS idx_face_cluster_member_face ON face_cluster_member(face_observation_id);
        CREATE INDEX IF NOT EXISTS idx_face_cluster_run_versions ON face_cluster_run(model_version, preprocessing_version, threshold);

        -- === People / face identity (production source of truth) ===
        -- Named people are durable identities. Keywords are a search/export
        -- projection, not the authority. Face assignments preserve the exact
        -- face observation and the cluster/model provenance that suggested it.
        CREATE SEQUENCE IF NOT EXISTS person_id_seq START 1;

        CREATE TABLE IF NOT EXISTS person (
            id INTEGER PRIMARY KEY DEFAULT nextval('person_id_seq'),
            display_name TEXT NOT NULL,
            normalized_name TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE UNIQUE INDEX IF NOT EXISTS idx_person_normalized_name ON person(normalized_name);

        CREATE TABLE IF NOT EXISTS person_face_assignment (
            face_observation_id INTEGER PRIMARY KEY,
            person_id INTEGER NOT NULL,
            image_id INTEGER NOT NULL,
            analyzed_image_id INTEGER NOT NULL,
            face_index INTEGER NOT NULL,
            assignment_source TEXT NOT NULL,
            face_cluster_run_id TEXT,
            face_cluster_id INTEGER,
            model_version TEXT,
            preprocessing_version TEXT,
            threshold DOUBLE,
            confidence_cosine DOUBLE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_person_face_assignment_person ON person_face_assignment(person_id);
        CREATE INDEX IF NOT EXISTS idx_person_face_assignment_image ON person_face_assignment(image_id);
        CREATE INDEX IF NOT EXISTS idx_person_face_assignment_cluster ON person_face_assignment(face_cluster_run_id, face_cluster_id);

        -- === Durable analysis jobs (background intelligent culling coordinator) ===
        -- One row per user/requested enrichment run. The current focus pass uses
        -- this as durable foreground state; the future helper/agent will claim
        -- and update the same rows after the app exits. This table is separate
        -- from image-level scalar facts so curation and analysis remain
        -- disentangled. New table only: no ALTER ... ADD COLUMN ... DEFAULT path.
        CREATE SEQUENCE IF NOT EXISTS analysis_job_id_seq START 1;

        CREATE TABLE IF NOT EXISTS analysis_jobs (
            id INTEGER PRIMARY KEY DEFAULT nextval('analysis_job_id_seq'),
            job_kind TEXT NOT NULL,              -- focus_quality / subject_detection / ...
            scope_kind TEXT NOT NULL,            -- whole_catalogue / selection / path_prefix / ...
            scope_value TEXT,                    -- optional serialized scope payload
            algorithm_version TEXT NOT NULL,
            analysis_run_id TEXT NOT NULL UNIQUE,
            status TEXT NOT NULL,                -- queued / running / cancelling / cancelled / completed / failed
            total_candidate_count BIGINT NOT NULL,
            processed_count BIGINT NOT NULL,
            completed_count BIGINT NOT NULL,
            skipped_count BIGINT NOT NULL,
            failed_count BIGINT NOT NULL,
            updated_count BIGINT NOT NULL,
            cancel_requested BOOLEAN NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            started_at TIMESTAMP,
            updated_at TIMESTAMP,
            finished_at TIMESTAMP,
            last_error TEXT,
            current_image_id BIGINT,
            current_file_path TEXT,
            current_started_at TIMESTAMP,
            last_timeout_image_id BIGINT,
            last_timeout_file_path TEXT,
            last_timeout_at TIMESTAMP
        );

        ALTER TABLE analysis_jobs ADD COLUMN IF NOT EXISTS current_image_id BIGINT;
        ALTER TABLE analysis_jobs ADD COLUMN IF NOT EXISTS current_file_path TEXT;
        ALTER TABLE analysis_jobs ADD COLUMN IF NOT EXISTS current_started_at TIMESTAMP;
        ALTER TABLE analysis_jobs ADD COLUMN IF NOT EXISTS last_timeout_image_id BIGINT;
        ALTER TABLE analysis_jobs ADD COLUMN IF NOT EXISTS last_timeout_file_path TEXT;
        ALTER TABLE analysis_jobs ADD COLUMN IF NOT EXISTS last_timeout_at TIMESTAMP;

        CREATE INDEX IF NOT EXISTS idx_analysis_jobs_kind_status ON analysis_jobs(job_kind, status);
        CREATE INDEX IF NOT EXISTS idx_analysis_jobs_run_id ON analysis_jobs(analysis_run_id);

        -- === Operation Log (S113; Docs/DESIGN-Operation-Log.md) ===
        -- Durable per-run operation records + noteworthy events (skips,
        -- failures, losses) on the analysis_jobs precedent. Write-always,
        -- filter-at-view; successes are carried by the run counters, not
        -- per-row entries. Brand-new tables = CREATE-time DDL only, so the
        -- S62 ALTER-with-DEFAULT WAL hazard never arises.
        CREATE SEQUENCE IF NOT EXISTS operation_log_id_seq START 1;
        CREATE SEQUENCE IF NOT EXISTS operation_log_entry_id_seq START 1;

        CREATE TABLE IF NOT EXISTS operation_log (
            id INTEGER PRIMARY KEY DEFAULT nextval('operation_log_id_seq'),
            kind TEXT NOT NULL,              -- scan / lr_import / apple_import / sync / copy / zip / materialize / backup / restore / lr_export
            started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            finished_at TIMESTAMP,
            outcome TEXT,                    -- NULL while running; completed / cancelled / failed
            total_count BIGINT NOT NULL,
            succeeded_count BIGINT NOT NULL,
            skipped_count BIGINT NOT NULL,
            failed_count BIGINT NOT NULL,
            summary TEXT
        );

        CREATE TABLE IF NOT EXISTS operation_log_entry (
            id INTEGER PRIMARY KEY DEFAULT nextval('operation_log_entry_id_seq'),
            run_id INTEGER NOT NULL,
            severity TEXT NOT NULL,          -- info / warning / error
            file_path TEXT,
            reason_code TEXT NOT NULL,       -- stable token, e.g. unreadable / copy_failed
            message TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            -- S125 file facts (cloud-safe stat metadata captured at write time so
            -- a support reader can find AND identify the file). Nullable, NO
            -- default (S62 WAL-replay rule); dates are ISO-8601 TEXT.
            file_byte_size BIGINT,
            file_created_at TEXT,
            file_modified_at TEXT
        );

        -- Pre-S125 catalogues gain the three file-fact columns here. No default
        -- (the S62 ALTER-with-DEFAULT wedge), so no backfill: rows written before
        -- S125 keep NULL facts and are still actionable via their stored path.
        ALTER TABLE operation_log_entry ADD COLUMN IF NOT EXISTS file_byte_size BIGINT;
        ALTER TABLE operation_log_entry ADD COLUMN IF NOT EXISTS file_created_at TEXT;
        ALTER TABLE operation_log_entry ADD COLUMN IF NOT EXISTS file_modified_at TEXT;

        CREATE INDEX IF NOT EXISTS idx_operation_log_entry_run ON operation_log_entry(run_id);
        CREATE INDEX IF NOT EXISTS idx_operation_log_entry_run_severity ON operation_log_entry(run_id, severity);

        -- === Similar-photo grouping (Intelligent Culling, S94) ===
        -- Vision feature-print comparison runs in Swift, then writes only durable
        -- group membership here. Singletons have no row. `group_id` is the
        -- representative image id, which keeps groups stable and readable without
        -- a separate sequence/table for v1.
        CREATE TABLE IF NOT EXISTS similar_photo_group_member (
            image_id INTEGER PRIMARY KEY,
            group_id INTEGER NOT NULL,
            representative_id INTEGER NOT NULL,
            member_rank INTEGER NOT NULL,
            distance_to_representative DOUBLE,
            algorithm_version TEXT NOT NULL,
            threshold DOUBLE NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_similar_photo_group ON similar_photo_group_member(group_id);
        CREATE INDEX IF NOT EXISTS idx_similar_photo_rep ON similar_photo_group_member(representative_id);
        CREATE INDEX IF NOT EXISTS idx_similar_photo_algorithm ON similar_photo_group_member(algorithm_version);

        -- Durable Vision featureprints for resumable similar-photo grouping.
        -- The Swift runner owns the Vision observation bytes; core stores them
        -- by image/algorithm/source stamp so cancelled runs do not regenerate
        -- the expensive featureprint work.
        CREATE TABLE IF NOT EXISTS similar_photo_featureprint (
            image_id INTEGER NOT NULL,
            algorithm_version TEXT NOT NULL,
            source_stamp TEXT NOT NULL,
            featureprint_blob BLOB NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (image_id, algorithm_version)
        );

        CREATE INDEX IF NOT EXISTS idx_similar_featureprint_algorithm ON similar_photo_featureprint(algorithm_version);

        -- Resumable/progressive grouping checkpoints. A unit is complete only
        -- for the deterministic candidate boundary that wrote it; callers match
        -- unit index plus start/end ids before skipping.
        CREATE TABLE IF NOT EXISTS similar_photo_group_work_unit (
            algorithm_version TEXT NOT NULL,
            scope_key TEXT NOT NULL,
            unit_index BIGINT NOT NULL,
            start_image_id INTEGER NOT NULL,
            end_image_id INTEGER NOT NULL,
            candidate_count BIGINT NOT NULL,
            member_count BIGINT NOT NULL,
            status TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (algorithm_version, scope_key, unit_index)
        );

        CREATE INDEX IF NOT EXISTS idx_similar_work_unit_scope ON similar_photo_group_work_unit(algorithm_version, scope_key, status);

        -- Content-keyed grouping checkpoints (item 7a; DESIGN-Pipeline-Scale-
        -- Hardening §1). Supersedes similar_photo_group_work_unit above
        -- (kept for existing catalogues, never read again). unit_key = the
        -- runner's SHA-256 over the unit's expanded candidate window, so a
        -- row survives corpus changes elsewhere; row-exists = complete; no
        -- scope_key (a content key cannot false-match across scopes).
        CREATE TABLE IF NOT EXISTS similar_photo_unit_checkpoint (
            algorithm_version TEXT NOT NULL,
            unit_key TEXT NOT NULL,
            start_image_id INTEGER NOT NULL,
            end_image_id INTEGER NOT NULL,
            anchor_count BIGINT NOT NULL,
            member_count BIGINT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (algorithm_version, unit_key)
        );

        -- === Keyword system (Session 45; Docs/DESIGN-Keyword-System.md) ===
        -- Hierarchical keywords in ONE table. Each applied keyword PATH is
        -- materialized as one row per ancestor level; each row carries `label`
        -- (that node, = last path segment) and `path` (root->that node,
        -- U+001F-joined). Soft-hide via `status` (1 = active/retained, 0 =
        -- hidden); `created_at`/`hidden_at` move together. `label` is the hot
        -- query key; `path` is the structural truth. No stored `level` (it is
        -- derivable from `path`).
        CREATE SEQUENCE IF NOT EXISTS keyword_id_seq START 1;

        CREATE TABLE IF NOT EXISTS keyword (
            id INTEGER PRIMARY KEY DEFAULT nextval('keyword_id_seq'),
            image_id INTEGER NOT NULL,          -- -> images.id (the "image pointer")
            label TEXT NOT NULL,                -- this node's text (= last path segment)
            path TEXT NOT NULL,                 -- root->this node, U+001F-separated
            status INTEGER NOT NULL DEFAULT 1,  -- 1 = active, 0 = hidden (soft-delete)
            origin INTEGER NOT NULL DEFAULT 1,  -- bitmask: 1 = user/import, 2 = auto-categorization, 4 = face/person projection
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            hidden_at TIMESTAMP,                -- set when status->0; NULL while active
            collection BOOLEAN NOT NULL DEFAULT FALSE,  -- Collections-panel membership; orthogonal to status (keyword search stays oblivious)
            color BOOLEAN NOT NULL DEFAULT FALSE,       -- S66: this label is a COLOR (custom Lightroom color-label text); third independent switch
            is_video BOOLEAN NOT NULL DEFAULT FALSE     -- S70: denormalized media-type discriminator (= images.is_video of the row this points to); join-free media filtering on keyword
        );

        CREATE INDEX IF NOT EXISTS idx_keyword_image_id ON keyword(image_id);
        CREATE INDEX IF NOT EXISTS idx_keyword_label ON keyword(label);
        CREATE INDEX IF NOT EXISTS idx_keyword_path ON keyword(path);
        CREATE INDEX IF NOT EXISTS idx_keyword_status ON keyword(status);

        -- Migration for pre-existing catalogues (no-op on a fresh DB, where the
        -- CREATE TABLE above already carries the column). Mirrors the images ALTERs:
        -- add the column WITHOUT a DEFAULT, then backfill the literal. An
        -- `ALTER TABLE ... ADD COLUMN ... DEFAULT <expr>` does NOT survive WAL
        -- replay — on reopen DuckDB re-binds the default with no database context
        -- set and throws an internal error (GetDefaultDatabase), wedging the whole
        -- catalogue. `collection = TRUE` excludes the NULLs anyway; the backfill
        -- just makes it tidy.
        ALTER TABLE keyword ADD COLUMN IF NOT EXISTS collection BOOLEAN;
        UPDATE keyword SET collection = FALSE WHERE collection IS NULL;

        -- Same migration shape for the color switch (S66). A pre-existing
        -- catalogue's color-derived rows can't be retro-identified (that's the
        -- gap this column closes) — they backfill FALSE and a re-import marks
        -- them.
        ALTER TABLE keyword ADD COLUMN IF NOT EXISTS color BOOLEAN;
        UPDATE keyword SET color = FALSE WHERE color IS NULL;

        -- Keyword provenance (S93): separate from `status`, which remains the
        -- active/hidden switch. Bitmask: 1 = user/import-applied, 2 =
        -- auto-categorization, 3 = both. Existing rows backfill user-origin;
        -- development catalogues are normally rebuilt fresh, but this keeps the
        -- schema reopen path total.
        ALTER TABLE keyword ADD COLUMN IF NOT EXISTS origin INTEGER;
        UPDATE keyword SET origin = 1 WHERE origin IS NULL;
        CREATE INDEX IF NOT EXISTS idx_keyword_origin ON keyword(origin);

        -- S70: denormalized media-type discriminator on each keyword row — a copy
        -- of images.is_video for the row it points to. is_video is immutable, so
        -- the copy never drifts; backfilled FROM the referenced image (correlated
        -- subquery), idempotent via the IS NULL guard so it runs once. Lets the
        -- keyword-vocabulary / media-count queries filter without a keyword-images
        -- join on the highest-cardinality table.
        ALTER TABLE keyword ADD COLUMN IF NOT EXISTS is_video BOOLEAN;
        UPDATE keyword SET is_video =
            COALESCE((SELECT i.is_video FROM images i WHERE i.id = keyword.image_id), FALSE)
            WHERE is_video IS NULL;

        -- Active-only view: ALL normal keyword reads/queries hit this so the
        -- status filter can never be forgotten. Recovery reads the raw table.
        CREATE OR REPLACE VIEW keyword_visible AS
            SELECT * FROM keyword WHERE status = 1;

        -- === Videos (Lightroom import; Docs/DESIGN-Lightroom-Catalog-Import.md §8) ===
        -- Video assets live in their OWN table, NOT in `images` (video is not an
        -- ImageKind). Catalog-only for v1: metadata + curation. Poster-frame
        -- thumbnails + playback are Stage 6 (AVFoundation). The column shape
        -- mirrors `images` where they overlap (file props, timestamps, curation)
        -- so the two stay consistent and no migration is needed when videos
        -- become first-class. Video-specific columns: duration_seconds /
        -- frame_rate (decoded Swift-side from AgVideoInfo's hex QuickTime
        -- rationals), has_audio, video_kind (mov/mp4/mpeg by extension).
        -- Populated by merge_lightroom_videos (same ON CONFLICT(file_path) upsert
        -- pattern as the images merge). Sequence PK because DuckDB 1.2.2 drops
        -- GENERATED ... IDENTITY (same reason as images_id_seq).
        CREATE SEQUENCE IF NOT EXISTS videos_id_seq START 1;

        CREATE TABLE IF NOT EXISTS videos (
            id INTEGER PRIMARY KEY DEFAULT nextval('videos_id_seq'),

            -- File-system properties (mirror images)
            file_path TEXT NOT NULL UNIQUE,
            file_size BIGINT NOT NULL,
            file_name TEXT NOT NULL,
            file_extension TEXT,
            directory_path VARCHAR,
            created_timestamp INTEGER NOT NULL,   -- Unix epoch seconds
            modified_timestamp INTEGER NOT NULL,  -- Unix epoch seconds

            -- Capture / media metadata
            capture_datetime TEXT,                -- ISO 8601
            pixel_width INTEGER,
            pixel_height INTEGER,
            duration_seconds DOUBLE,              -- AgVideoInfo.duration (decoded)
            frame_rate DOUBLE,                    -- AgVideoInfo.frame_rate (decoded)
            has_audio BOOLEAN,
            video_kind TEXT,                      -- 'mov' / 'mp4' / 'mpeg' (by extension)

            -- Curation (LR rates/flags/labels videos too)
            rating INTEGER,
            flag TEXT,
            color_label TEXT,

            -- Audit
            indexed_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_videos_capture_datetime ON videos(capture_datetime);
        CREATE INDEX IF NOT EXISTS idx_videos_rating ON videos(rating);
        CREATE INDEX IF NOT EXISTS idx_videos_directory_path ON videos(directory_path);

        -- === Saved Queries (Session 63; Docs/DESIGN-Saved-Queries.md) ===
        -- A saved Find in Gallery query: the RECIPE (criterion rows), never the
        -- results. `saved_query_criterion` mirrors the QueryPredicate wire
        -- struct exactly, plus placement: `position` (1-based slot in the
        -- sentence) and `connector` (how the row joins everything to its LEFT
        -- in the builder's left-to-right fold; NULL at position 1). One row per
        -- criterion — repeated subjects are simply more rows. Migrations stay
        -- WAL-safe: bare ALTER ADD COLUMN only, never with a DEFAULT (the S62
        -- lesson) — see the S65 num/num_end ALTERs below.
        CREATE SEQUENCE IF NOT EXISTS saved_query_id_seq START 1;

        CREATE TABLE IF NOT EXISTS saved_query (
            id INTEGER PRIMARY KEY DEFAULT nextval('saved_query_id_seq'),
            name TEXT NOT NULL,                 -- unique by construction (save_query suffixes collisions)
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS saved_query_criterion (
            query_id INTEGER NOT NULL,          -- -> saved_query.id
            position INTEGER NOT NULL,          -- 1-based slot in the sentence
            connector TEXT,                     -- 'and' / 'or' / 'xor'; NULL at position 1
            kind TEXT NOT NULL,                 -- QueryPredicate.kind (the subject discriminator)
            op TEXT,                            -- QueryPredicate.op
            value TEXT,                         -- QueryPredicate.value
            day TEXT,                           -- QueryPredicate.day ("YYYY:MM:DD")
            day_end TEXT,                       -- QueryPredicate.day_end
            stars INTEGER,                      -- QueryPredicate.stars
            num DOUBLE,                         -- QueryPredicate.num (S65 numeric subjects)
            num_end DOUBLE                      -- QueryPredicate.num_end ("between" upper bound)
        );

        -- S65: catalogues whose saved_query_criterion predates the numeric
        -- subjects gain the two columns here — bare ALTER, NO DEFAULT (the S62
        -- WAL-replay lesson), and no backfill: NULL is the correct resting
        -- value for every pre-numeric row.
        ALTER TABLE saved_query_criterion ADD COLUMN IF NOT EXISTS num DOUBLE;
        ALTER TABLE saved_query_criterion ADD COLUMN IF NOT EXISTS num_end DOUBLE;

        CREATE INDEX IF NOT EXISTS idx_saved_query_criterion_query ON saved_query_criterion(query_id);

        -- === Folder Sync (Session 68; Docs/DESIGN-Folder-Sync.md) ===
        -- One row per catalogued directory: that directory's on-disk mtime
        -- (epoch seconds, as stat reports it) recorded when the directory was
        -- last scanned or synced. The SourceLocationMonitor sweep compares a
        -- fresh stat against last_sync_mtime — INEQUALITY, not greater-than
        -- (a folder restored from backup moves BACKWARD and is still changed).
        -- A brand-new table needs no ALTER migration, so the S62 WAL-replay
        -- hazard cannot apply here; CREATE-time shape is final.
        CREATE TABLE IF NOT EXISTS directory_sync_state (
            directory_path  TEXT PRIMARY KEY,
            last_sync_mtime BIGINT NOT NULL
        );
