// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(photolibrariancoreFFI)
import photolibrariancoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_photolibrariancore_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_photolibrariancore_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePhotolibrariancoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct FilePathsResult: Equatable, Hashable {
    public var ok: Bool
    public var paths: [String]
    public var errorMessage: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ok: Bool, paths: [String], errorMessage: String?) {
        self.ok = ok
        self.paths = paths
        self.errorMessage = errorMessage
    }

    

    
}

#if compiler(>=6)
extension FilePathsResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFilePathsResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FilePathsResult {
        return
            try FilePathsResult(
                ok: FfiConverterBool.read(from: &buf), 
                paths: FfiConverterSequenceString.read(from: &buf), 
                errorMessage: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FilePathsResult, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.ok, into: &buf)
        FfiConverterSequenceString.write(value.paths, into: &buf)
        FfiConverterOptionString.write(value.errorMessage, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilePathsResult_lift(_ buf: RustBuffer) throws -> FilePathsResult {
    return try FfiConverterTypeFilePathsResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilePathsResult_lower(_ value: FilePathsResult) -> RustBuffer {
    return FfiConverterTypeFilePathsResult.lower(value)
}


public struct ImageMetadata: Equatable, Hashable {
    public var filePath: String
    public var fileSize: UInt64
    public var fileName: String
    public var fileExtension: String?
    public var createdTimestamp: Int64
    public var modifiedTimestamp: Int64
    public var cameraMake: String?
    public var cameraModel: String?
    public var lensModel: String?
    public var focalLength: Double?
    public var aperture: Double?
    public var shutterSpeed: Double?
    public var iso: UInt32?
    public var captureDatetime: String?
    public var pixelWidth: UInt32?
    public var pixelHeight: UInt32?
    public var colorSpace: String?
    public var bitDepth: UInt32?
    public var gpsLatitude: Double?
    public var gpsLongitude: Double?
    public var gpsAltitude: Double?
    public var copyright: String?
    public var creator: String?
    public var description: String?
    public var rating: UInt8?
    public var flag: String?
    public var colorLabel: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(filePath: String, fileSize: UInt64, fileName: String, fileExtension: String?, createdTimestamp: Int64, modifiedTimestamp: Int64, cameraMake: String?, cameraModel: String?, lensModel: String?, focalLength: Double?, aperture: Double?, shutterSpeed: Double?, iso: UInt32?, captureDatetime: String?, pixelWidth: UInt32?, pixelHeight: UInt32?, colorSpace: String?, bitDepth: UInt32?, gpsLatitude: Double?, gpsLongitude: Double?, gpsAltitude: Double?, copyright: String?, creator: String?, description: String?, rating: UInt8?, flag: String?, colorLabel: String?) {
        self.filePath = filePath
        self.fileSize = fileSize
        self.fileName = fileName
        self.fileExtension = fileExtension
        self.createdTimestamp = createdTimestamp
        self.modifiedTimestamp = modifiedTimestamp
        self.cameraMake = cameraMake
        self.cameraModel = cameraModel
        self.lensModel = lensModel
        self.focalLength = focalLength
        self.aperture = aperture
        self.shutterSpeed = shutterSpeed
        self.iso = iso
        self.captureDatetime = captureDatetime
        self.pixelWidth = pixelWidth
        self.pixelHeight = pixelHeight
        self.colorSpace = colorSpace
        self.bitDepth = bitDepth
        self.gpsLatitude = gpsLatitude
        self.gpsLongitude = gpsLongitude
        self.gpsAltitude = gpsAltitude
        self.copyright = copyright
        self.creator = creator
        self.description = description
        self.rating = rating
        self.flag = flag
        self.colorLabel = colorLabel
    }

    

    
}

#if compiler(>=6)
extension ImageMetadata: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImageMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImageMetadata {
        return
            try ImageMetadata(
                filePath: FfiConverterString.read(from: &buf), 
                fileSize: FfiConverterUInt64.read(from: &buf), 
                fileName: FfiConverterString.read(from: &buf), 
                fileExtension: FfiConverterOptionString.read(from: &buf), 
                createdTimestamp: FfiConverterInt64.read(from: &buf), 
                modifiedTimestamp: FfiConverterInt64.read(from: &buf), 
                cameraMake: FfiConverterOptionString.read(from: &buf), 
                cameraModel: FfiConverterOptionString.read(from: &buf), 
                lensModel: FfiConverterOptionString.read(from: &buf), 
                focalLength: FfiConverterOptionDouble.read(from: &buf), 
                aperture: FfiConverterOptionDouble.read(from: &buf), 
                shutterSpeed: FfiConverterOptionDouble.read(from: &buf), 
                iso: FfiConverterOptionUInt32.read(from: &buf), 
                captureDatetime: FfiConverterOptionString.read(from: &buf), 
                pixelWidth: FfiConverterOptionUInt32.read(from: &buf), 
                pixelHeight: FfiConverterOptionUInt32.read(from: &buf), 
                colorSpace: FfiConverterOptionString.read(from: &buf), 
                bitDepth: FfiConverterOptionUInt32.read(from: &buf), 
                gpsLatitude: FfiConverterOptionDouble.read(from: &buf), 
                gpsLongitude: FfiConverterOptionDouble.read(from: &buf), 
                gpsAltitude: FfiConverterOptionDouble.read(from: &buf), 
                copyright: FfiConverterOptionString.read(from: &buf), 
                creator: FfiConverterOptionString.read(from: &buf), 
                description: FfiConverterOptionString.read(from: &buf), 
                rating: FfiConverterOptionUInt8.read(from: &buf), 
                flag: FfiConverterOptionString.read(from: &buf), 
                colorLabel: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ImageMetadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.filePath, into: &buf)
        FfiConverterUInt64.write(value.fileSize, into: &buf)
        FfiConverterString.write(value.fileName, into: &buf)
        FfiConverterOptionString.write(value.fileExtension, into: &buf)
        FfiConverterInt64.write(value.createdTimestamp, into: &buf)
        FfiConverterInt64.write(value.modifiedTimestamp, into: &buf)
        FfiConverterOptionString.write(value.cameraMake, into: &buf)
        FfiConverterOptionString.write(value.cameraModel, into: &buf)
        FfiConverterOptionString.write(value.lensModel, into: &buf)
        FfiConverterOptionDouble.write(value.focalLength, into: &buf)
        FfiConverterOptionDouble.write(value.aperture, into: &buf)
        FfiConverterOptionDouble.write(value.shutterSpeed, into: &buf)
        FfiConverterOptionUInt32.write(value.iso, into: &buf)
        FfiConverterOptionString.write(value.captureDatetime, into: &buf)
        FfiConverterOptionUInt32.write(value.pixelWidth, into: &buf)
        FfiConverterOptionUInt32.write(value.pixelHeight, into: &buf)
        FfiConverterOptionString.write(value.colorSpace, into: &buf)
        FfiConverterOptionUInt32.write(value.bitDepth, into: &buf)
        FfiConverterOptionDouble.write(value.gpsLatitude, into: &buf)
        FfiConverterOptionDouble.write(value.gpsLongitude, into: &buf)
        FfiConverterOptionDouble.write(value.gpsAltitude, into: &buf)
        FfiConverterOptionString.write(value.copyright, into: &buf)
        FfiConverterOptionString.write(value.creator, into: &buf)
        FfiConverterOptionString.write(value.description, into: &buf)
        FfiConverterOptionUInt8.write(value.rating, into: &buf)
        FfiConverterOptionString.write(value.flag, into: &buf)
        FfiConverterOptionString.write(value.colorLabel, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageMetadata_lift(_ buf: RustBuffer) throws -> ImageMetadata {
    return try FfiConverterTypeImageMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageMetadata_lower(_ value: ImageMetadata) -> RustBuffer {
    return FfiConverterTypeImageMetadata.lower(value)
}


public struct ImageRecord: Equatable, Hashable {
    public var id: Int64
    public var indexedTimestamp: String
    public var filePath: String
    public var fileSize: UInt64
    public var fileName: String
    public var fileExtension: String?
    public var createdTimestamp: Int64
    public var modifiedTimestamp: Int64
    public var cameraMake: String?
    public var cameraModel: String?
    public var lensModel: String?
    public var focalLength: Double?
    public var aperture: Double?
    public var shutterSpeed: Double?
    public var iso: UInt32?
    public var captureDatetime: String?
    public var pixelWidth: UInt32?
    public var pixelHeight: UInt32?
    public var colorSpace: String?
    public var bitDepth: UInt32?
    public var gpsLatitude: Double?
    public var gpsLongitude: Double?
    public var gpsAltitude: Double?
    public var copyright: String?
    public var creator: String?
    public var description: String?
    public var rating: UInt8?
    public var flag: String?
    public var colorLabel: String?
    public var rotation: Int32
    public var duplicateGroupId: Int64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, indexedTimestamp: String, filePath: String, fileSize: UInt64, fileName: String, fileExtension: String?, createdTimestamp: Int64, modifiedTimestamp: Int64, cameraMake: String?, cameraModel: String?, lensModel: String?, focalLength: Double?, aperture: Double?, shutterSpeed: Double?, iso: UInt32?, captureDatetime: String?, pixelWidth: UInt32?, pixelHeight: UInt32?, colorSpace: String?, bitDepth: UInt32?, gpsLatitude: Double?, gpsLongitude: Double?, gpsAltitude: Double?, copyright: String?, creator: String?, description: String?, rating: UInt8?, flag: String?, colorLabel: String?, rotation: Int32, duplicateGroupId: Int64?) {
        self.id = id
        self.indexedTimestamp = indexedTimestamp
        self.filePath = filePath
        self.fileSize = fileSize
        self.fileName = fileName
        self.fileExtension = fileExtension
        self.createdTimestamp = createdTimestamp
        self.modifiedTimestamp = modifiedTimestamp
        self.cameraMake = cameraMake
        self.cameraModel = cameraModel
        self.lensModel = lensModel
        self.focalLength = focalLength
        self.aperture = aperture
        self.shutterSpeed = shutterSpeed
        self.iso = iso
        self.captureDatetime = captureDatetime
        self.pixelWidth = pixelWidth
        self.pixelHeight = pixelHeight
        self.colorSpace = colorSpace
        self.bitDepth = bitDepth
        self.gpsLatitude = gpsLatitude
        self.gpsLongitude = gpsLongitude
        self.gpsAltitude = gpsAltitude
        self.copyright = copyright
        self.creator = creator
        self.description = description
        self.rating = rating
        self.flag = flag
        self.colorLabel = colorLabel
        self.rotation = rotation
        self.duplicateGroupId = duplicateGroupId
    }

    

    
}

#if compiler(>=6)
extension ImageRecord: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImageRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImageRecord {
        return
            try ImageRecord(
                id: FfiConverterInt64.read(from: &buf), 
                indexedTimestamp: FfiConverterString.read(from: &buf), 
                filePath: FfiConverterString.read(from: &buf), 
                fileSize: FfiConverterUInt64.read(from: &buf), 
                fileName: FfiConverterString.read(from: &buf), 
                fileExtension: FfiConverterOptionString.read(from: &buf), 
                createdTimestamp: FfiConverterInt64.read(from: &buf), 
                modifiedTimestamp: FfiConverterInt64.read(from: &buf), 
                cameraMake: FfiConverterOptionString.read(from: &buf), 
                cameraModel: FfiConverterOptionString.read(from: &buf), 
                lensModel: FfiConverterOptionString.read(from: &buf), 
                focalLength: FfiConverterOptionDouble.read(from: &buf), 
                aperture: FfiConverterOptionDouble.read(from: &buf), 
                shutterSpeed: FfiConverterOptionDouble.read(from: &buf), 
                iso: FfiConverterOptionUInt32.read(from: &buf), 
                captureDatetime: FfiConverterOptionString.read(from: &buf), 
                pixelWidth: FfiConverterOptionUInt32.read(from: &buf), 
                pixelHeight: FfiConverterOptionUInt32.read(from: &buf), 
                colorSpace: FfiConverterOptionString.read(from: &buf), 
                bitDepth: FfiConverterOptionUInt32.read(from: &buf), 
                gpsLatitude: FfiConverterOptionDouble.read(from: &buf), 
                gpsLongitude: FfiConverterOptionDouble.read(from: &buf), 
                gpsAltitude: FfiConverterOptionDouble.read(from: &buf), 
                copyright: FfiConverterOptionString.read(from: &buf), 
                creator: FfiConverterOptionString.read(from: &buf), 
                description: FfiConverterOptionString.read(from: &buf), 
                rating: FfiConverterOptionUInt8.read(from: &buf), 
                flag: FfiConverterOptionString.read(from: &buf), 
                colorLabel: FfiConverterOptionString.read(from: &buf), 
                rotation: FfiConverterInt32.read(from: &buf), 
                duplicateGroupId: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: ImageRecord, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.indexedTimestamp, into: &buf)
        FfiConverterString.write(value.filePath, into: &buf)
        FfiConverterUInt64.write(value.fileSize, into: &buf)
        FfiConverterString.write(value.fileName, into: &buf)
        FfiConverterOptionString.write(value.fileExtension, into: &buf)
        FfiConverterInt64.write(value.createdTimestamp, into: &buf)
        FfiConverterInt64.write(value.modifiedTimestamp, into: &buf)
        FfiConverterOptionString.write(value.cameraMake, into: &buf)
        FfiConverterOptionString.write(value.cameraModel, into: &buf)
        FfiConverterOptionString.write(value.lensModel, into: &buf)
        FfiConverterOptionDouble.write(value.focalLength, into: &buf)
        FfiConverterOptionDouble.write(value.aperture, into: &buf)
        FfiConverterOptionDouble.write(value.shutterSpeed, into: &buf)
        FfiConverterOptionUInt32.write(value.iso, into: &buf)
        FfiConverterOptionString.write(value.captureDatetime, into: &buf)
        FfiConverterOptionUInt32.write(value.pixelWidth, into: &buf)
        FfiConverterOptionUInt32.write(value.pixelHeight, into: &buf)
        FfiConverterOptionString.write(value.colorSpace, into: &buf)
        FfiConverterOptionUInt32.write(value.bitDepth, into: &buf)
        FfiConverterOptionDouble.write(value.gpsLatitude, into: &buf)
        FfiConverterOptionDouble.write(value.gpsLongitude, into: &buf)
        FfiConverterOptionDouble.write(value.gpsAltitude, into: &buf)
        FfiConverterOptionString.write(value.copyright, into: &buf)
        FfiConverterOptionString.write(value.creator, into: &buf)
        FfiConverterOptionString.write(value.description, into: &buf)
        FfiConverterOptionUInt8.write(value.rating, into: &buf)
        FfiConverterOptionString.write(value.flag, into: &buf)
        FfiConverterOptionString.write(value.colorLabel, into: &buf)
        FfiConverterInt32.write(value.rotation, into: &buf)
        FfiConverterOptionInt64.write(value.duplicateGroupId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageRecord_lift(_ buf: RustBuffer) throws -> ImageRecord {
    return try FfiConverterTypeImageRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageRecord_lower(_ value: ImageRecord) -> RustBuffer {
    return FfiConverterTypeImageRecord.lower(value)
}


public struct ParsedFilename: Equatable, Hashable {
    public var stem: String
    public var extensionLower: String
    public var kind: ImageKind

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(stem: String, extensionLower: String, kind: ImageKind) {
        self.stem = stem
        self.extensionLower = extensionLower
        self.kind = kind
    }

    

    
}

#if compiler(>=6)
extension ParsedFilename: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParsedFilename: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParsedFilename {
        return
            try ParsedFilename(
                stem: FfiConverterString.read(from: &buf), 
                extensionLower: FfiConverterString.read(from: &buf), 
                kind: FfiConverterTypeImageKind.read(from: &buf)
        )
    }

    public static func write(_ value: ParsedFilename, into buf: inout [UInt8]) {
        FfiConverterString.write(value.stem, into: &buf)
        FfiConverterString.write(value.extensionLower, into: &buf)
        FfiConverterTypeImageKind.write(value.kind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedFilename_lift(_ buf: RustBuffer) throws -> ParsedFilename {
    return try FfiConverterTypeParsedFilename.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedFilename_lower(_ value: ParsedFilename) -> RustBuffer {
    return FfiConverterTypeParsedFilename.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ImageKind: Equatable, Hashable {
    
    case jpeg
    case raw
    case other





}

#if compiler(>=6)
extension ImageKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImageKind: FfiConverterRustBuffer {
    typealias SwiftType = ImageKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImageKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .jpeg
        
        case 2: return .raw
        
        case 3: return .other
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ImageKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .jpeg:
            writeInt(&buf, Int32(1))
        
        
        case .raw:
            writeInt(&buf, Int32(2))
        
        
        case .other:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageKind_lift(_ buf: RustBuffer) throws -> ImageKind {
    return try FfiConverterTypeImageKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageKind_lower(_ value: ImageKind) -> RustBuffer {
    return FfiConverterTypeImageKind.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeImageRecord: FfiConverterRustBuffer {
    typealias SwiftType = ImageRecord?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeImageRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeImageRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeImageMetadata: FfiConverterRustBuffer {
    typealias SwiftType = [ImageMetadata]

    public static func write(_ value: [ImageMetadata], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeImageMetadata.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ImageMetadata] {
        let len: Int32 = try readInt(&buf)
        var seq = [ImageMetadata]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeImageMetadata.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeImageRecord: FfiConverterRustBuffer {
    typealias SwiftType = [ImageRecord]

    public static func write(_ value: [ImageRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeImageRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ImageRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [ImageRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeImageRecord.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsurePhotolibrariancoreInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func classifyExtension(ext: String) -> ImageKind  {
    return try!  FfiConverterTypeImageKind_lift(try! rustCall() {
    uniffi_photolibrariancore_fn_func_classify_extension(
        FfiConverterString.lower(ext),$0
    )
})
}
public func findCounterpartImage(filePath: String)async  -> ImageRecord?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_find_counterpart_image(FfiConverterString.lower(filePath)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photolibrariancore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photolibrariancore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeImageRecord.lift,
            errorHandler: nil
            
        )
}
public func getAllImages(limit: UInt32, offset: UInt32, applyDuplicateFilter: Bool, applyRawJpegCollapse: Bool)async  -> [ImageRecord]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_all_images(FfiConverterUInt32.lower(limit),FfiConverterUInt32.lower(offset),FfiConverterBool.lower(applyDuplicateFilter),FfiConverterBool.lower(applyRawJpegCollapse)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photolibrariancore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photolibrariancore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeImageRecord.lift,
            errorHandler: nil
            
        )
}
public func getDestinationFamilyRecords(sampleFilePath: String, canonicalFileName: String)async  -> [ImageRecord]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_destination_family_records(FfiConverterString.lower(sampleFilePath),FfiConverterString.lower(canonicalFileName)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photolibrariancore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photolibrariancore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeImageRecord.lift,
            errorHandler: nil
            
        )
}
public func getDistinctDateStrings()async  -> [String]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_distinct_date_strings(
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photolibrariancore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photolibrariancore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceString.lift,
            errorHandler: nil
            
        )
}
public func getDistinctDirectoryPaths()async  -> [String]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_distinct_directory_paths(
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photolibrariancore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photolibrariancore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceString.lift,
            errorHandler: nil
            
        )
}
public func getFilePathsForFilters(pathPrefix: String, datePrefix: String, applyDuplicateFilter: Bool, applyRawJpegCollapse: Bool)async  -> FilePathsResult  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_file_paths_for_filters(FfiConverterString.lower(pathPrefix),FfiConverterString.lower(datePrefix),FfiConverterBool.lower(applyDuplicateFilter),FfiConverterBool.lower(applyRawJpegCollapse)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photolibrariancore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photolibrariancore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFilePathsResult_lift,
            errorHandler: nil
            
        )
}
public func getFilteredImageCount(datePrefix: String, applyDuplicateFilter: Bool, applyRawJpegCollapse: Bool)async  -> Int64  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_filtered_image_count(FfiConverterString.lower(datePrefix),FfiConverterBool.lower(applyDuplicateFilter),FfiConverterBool.lower(applyRawJpegCollapse)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_i64,
            completeFunc: ffi_photolibrariancore_rust_future_complete_i64,
            freeFunc: ffi_photolibrariancore_rust_future_free_i64,
            liftFunc: FfiConverterInt64.lift,
            errorHandler: nil
            
        )
}
public func getImageCount(applyDuplicateFilter: Bool, applyRawJpegCollapse: Bool)async  -> UInt64  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_image_count(FfiConverterBool.lower(applyDuplicateFilter),FfiConverterBool.lower(applyRawJpegCollapse)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_u64,
            completeFunc: ffi_photolibrariancore_rust_future_complete_u64,
            freeFunc: ffi_photolibrariancore_rust_future_free_u64,
            liftFunc: FfiConverterUInt64.lift,
            errorHandler: nil
            
        )
}
public func getImageCountForFilters(pathPrefix: String, datePrefix: String, applyDuplicateFilter: Bool, applyRawJpegCollapse: Bool)async  -> Int64  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_image_count_for_filters(FfiConverterString.lower(pathPrefix),FfiConverterString.lower(datePrefix),FfiConverterBool.lower(applyDuplicateFilter),FfiConverterBool.lower(applyRawJpegCollapse)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_i64,
            completeFunc: ffi_photolibrariancore_rust_future_complete_i64,
            freeFunc: ffi_photolibrariancore_rust_future_free_i64,
            liftFunc: FfiConverterInt64.lift,
            errorHandler: nil
            
        )
}
public func getImageCountForPathPrefix(pathPrefix: String, applyDuplicateFilter: Bool, applyRawJpegCollapse: Bool)async  -> Int64  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_image_count_for_path_prefix(FfiConverterString.lower(pathPrefix),FfiConverterBool.lower(applyDuplicateFilter),FfiConverterBool.lower(applyRawJpegCollapse)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_i64,
            completeFunc: ffi_photolibrariancore_rust_future_complete_i64,
            freeFunc: ffi_photolibrariancore_rust_future_free_i64,
            liftFunc: FfiConverterInt64.lift,
            errorHandler: nil
            
        )
}
public func getImageRecordsForFilters(pathPrefix: String, datePrefix: String, applyDuplicateFilter: Bool, applyRawJpegCollapse: Bool)async  -> [ImageRecord]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_image_records_for_filters(FfiConverterString.lower(pathPrefix),FfiConverterString.lower(datePrefix),FfiConverterBool.lower(applyDuplicateFilter),FfiConverterBool.lower(applyRawJpegCollapse)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photolibrariancore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photolibrariancore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeImageRecord.lift,
            errorHandler: nil
            
        )
}
public func getImagesFiltered(limit: Int64, offset: Int64, datePrefix: String, applyDuplicateFilter: Bool, applyRawJpegCollapse: Bool)async  -> [ImageRecord]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_images_filtered(FfiConverterInt64.lower(limit),FfiConverterInt64.lower(offset),FfiConverterString.lower(datePrefix),FfiConverterBool.lower(applyDuplicateFilter),FfiConverterBool.lower(applyRawJpegCollapse)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photolibrariancore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photolibrariancore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeImageRecord.lift,
            errorHandler: nil
            
        )
}
public func getImagesForPathPrefix(limit: Int64, offset: Int64, pathPrefix: String, datePrefix: String, applyDuplicateFilter: Bool, applyRawJpegCollapse: Bool)async  -> [ImageRecord]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_images_for_path_prefix(FfiConverterInt64.lower(limit),FfiConverterInt64.lower(offset),FfiConverterString.lower(pathPrefix),FfiConverterString.lower(datePrefix),FfiConverterBool.lower(applyDuplicateFilter),FfiConverterBool.lower(applyRawJpegCollapse)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photolibrariancore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photolibrariancore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeImageRecord.lift,
            errorHandler: nil
            
        )
}
public func getImagesSorted(limit: UInt32, offset: UInt32, applyDuplicateFilter: Bool, applyRawJpegCollapse: Bool)async  -> [ImageRecord]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_get_images_sorted(FfiConverterUInt32.lower(limit),FfiConverterUInt32.lower(offset),FfiConverterBool.lower(applyDuplicateFilter),FfiConverterBool.lower(applyRawJpegCollapse)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_rust_buffer,
            completeFunc: ffi_photolibrariancore_rust_future_complete_rust_buffer,
            freeFunc: ffi_photolibrariancore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeImageRecord.lift,
            errorHandler: nil
            
        )
}
public func getJpegExtensions() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_photolibrariancore_fn_func_get_jpeg_extensions($0
    )
})
}
public func getRawExtensions() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_photolibrariancore_fn_func_get_raw_extensions($0
    )
})
}
public func ingestMetadata(metadata: [ImageMetadata])async  -> UInt32  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_ingest_metadata(FfiConverterSequenceTypeImageMetadata.lower(metadata)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_u32,
            completeFunc: ffi_photolibrariancore_rust_future_complete_u32,
            freeFunc: ffi_photolibrariancore_rust_future_free_u32,
            liftFunc: FfiConverterUInt32.lift,
            errorHandler: nil
            
        )
}
public func initializeCatalogue(cataloguePath: String)async  -> Bool  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_initialize_catalogue(FfiConverterString.lower(cataloguePath)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_i8,
            completeFunc: ffi_photolibrariancore_rust_future_complete_i8,
            freeFunc: ffi_photolibrariancore_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: nil
            
        )
}
public func parseFilename(fileName: String) -> ParsedFilename  {
    return try!  FfiConverterTypeParsedFilename_lift(try! rustCall() {
    uniffi_photolibrariancore_fn_func_parse_filename(
        FfiConverterString.lower(fileName),$0
    )
})
}
public func updateImageRating(filePath: String, rating: UInt32)async  -> Bool  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_update_image_rating(FfiConverterString.lower(filePath),FfiConverterUInt32.lower(rating)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_i8,
            completeFunc: ffi_photolibrariancore_rust_future_complete_i8,
            freeFunc: ffi_photolibrariancore_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: nil
            
        )
}
public func updateImageRotation(filePath: String, degrees: Int32)async  -> Bool  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_photolibrariancore_fn_func_update_image_rotation(FfiConverterString.lower(filePath),FfiConverterInt32.lower(degrees)
                )
            },
            pollFunc: ffi_photolibrariancore_rust_future_poll_i8,
            completeFunc: ffi_photolibrariancore_rust_future_complete_i8,
            freeFunc: ffi_photolibrariancore_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: nil
            
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_photolibrariancore_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_classify_extension() != 38346) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_find_counterpart_image() != 51699) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_all_images() != 32796) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_destination_family_records() != 13287) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_distinct_date_strings() != 13981) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_distinct_directory_paths() != 54232) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_file_paths_for_filters() != 29177) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_filtered_image_count() != 33470) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_image_count() != 30319) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_image_count_for_filters() != 53360) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_image_count_for_path_prefix() != 38666) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_image_records_for_filters() != 7922) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_images_filtered() != 37905) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_images_for_path_prefix() != 15560) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_images_sorted() != 8765) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_jpeg_extensions() != 14521) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_get_raw_extensions() != 16992) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_ingest_metadata() != 1621) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_initialize_catalogue() != 29822) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_parse_filename() != 30612) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_update_image_rating() != 15118) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_photolibrariancore_checksum_func_update_image_rotation() != 63730) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePhotolibrariancoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all