use duckdb::{Connection, params};
use std::sync::{Arc, Mutex};
use std::path::PathBuf;

// UniFFI scaffolding
uniffi::include_scaffolding!("photolibrariancore");

// Global catalogue connection
// Wrapped in Arc<Mutex<>> for thread-safe access across UniFFI async calls
static CATALOGUE: once_cell::sync::Lazy<Arc<Mutex<Option<Connection>>>> =
    once_cell::sync::Lazy::new(|| Arc::new(Mutex::new(None)));

/// Represents the metadata for a single image file
/// This struct is defined in the .udl file and generated by UniFFI
#[derive(Debug, Clone)]
pub struct ImageMetadata {
    pub file_path: String,
    pub file_size: u64,
    pub file_name: String,
    pub file_extension: Option<String>,
    pub created_timestamp: i64,
    pub modified_timestamp: i64,

    // Camera/capture metadata
    pub camera_make: Option<String>,
    pub camera_model: Option<String>,
    pub lens_model: Option<String>,
    pub focal_length: Option<f64>,
    pub aperture: Option<f64>,
    pub shutter_speed: Option<f64>,
    pub iso: Option<u32>,
    pub capture_datetime: Option<String>,

    // Image properties
    pub pixel_width: Option<u32>,
    pub pixel_height: Option<u32>,
    pub color_space: Option<String>,
    pub bit_depth: Option<u32>,

    // GPS coordinates
    pub gps_latitude: Option<f64>,
    pub gps_longitude: Option<f64>,
    pub gps_altitude: Option<f64>,

    // IPTC/copyright
    pub copyright: Option<String>,
    pub creator: Option<String>,
    pub description: Option<String>,

    // Organization metadata
    pub rating: Option<u8>,
    pub flag: Option<String>,
    pub color_label: Option<String>,
}

/// Initialize the catalogue database at the given path
/// Creates the database file and schema if it doesn't exist
/// Returns true if successful, false on error
pub async fn initialize_catalogue(catalogue_path: String) -> bool {
    let path = PathBuf::from(&catalogue_path);

    // Create parent directory if it doesn't exist
    if let Some(parent) = path.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            eprintln!("Failed to create catalogue directory: {}", e);
            return false;
        }
    }

    // Open or create the database
    let conn = match Connection::open(&path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("Failed to open catalogue database: {}", e);
            return false;
        }
    };

    // Create the images table schema
    let schema = r#"
        CREATE TABLE IF NOT EXISTS images (
            id INTEGER PRIMARY KEY,
            file_path TEXT NOT NULL UNIQUE,
            file_size INTEGER NOT NULL,
            file_name TEXT NOT NULL,
            file_extension TEXT,
            created_timestamp INTEGER NOT NULL,
            modified_timestamp INTEGER NOT NULL,

            -- Camera/capture metadata
            camera_make TEXT,
            camera_model TEXT,
            lens_model TEXT,
            focal_length REAL,
            aperture REAL,
            shutter_speed REAL,
            iso INTEGER,
            capture_datetime TEXT,

            -- Image properties
            pixel_width INTEGER,
            pixel_height INTEGER,
            color_space TEXT,
            bit_depth INTEGER,

            -- GPS coordinates
            gps_latitude REAL,
            gps_longitude REAL,
            gps_altitude REAL,

            -- IPTC/copyright
            copyright TEXT,
            creator TEXT,
            description TEXT,

            -- Organization metadata
            rating INTEGER,
            flag TEXT,
            color_label TEXT,

            -- Indices for common queries
            indexed_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        -- Indexes for efficient filtering
        CREATE INDEX IF NOT EXISTS idx_camera_model ON images(camera_model);
        CREATE INDEX IF NOT EXISTS idx_capture_datetime ON images(capture_datetime);
        CREATE INDEX IF NOT EXISTS idx_created_timestamp ON images(created_timestamp);
        CREATE INDEX IF NOT EXISTS idx_file_extension ON images(file_extension);
        CREATE INDEX IF NOT EXISTS idx_rating ON images(rating);
        CREATE INDEX IF NOT EXISTS idx_flag ON images(flag);
        CREATE INDEX IF NOT EXISTS idx_color_label ON images(color_label);
    "#;

    if let Err(e) = conn.execute_batch(schema) {
        eprintln!("Failed to create catalogue schema: {}", e);
        return false;
    }

    // Store the connection in the global state
    let mut catalogue = CATALOGUE.lock().unwrap();
    *catalogue = Some(conn);

    true
}

/// Ingest a batch of image metadata records into the catalogue
/// Returns the number of records successfully inserted
/// Skips duplicates (based on file_path UNIQUE constraint)
pub async fn ingest_metadata(metadata: Vec<ImageMetadata>) -> u32 {
    let catalogue = CATALOGUE.lock().unwrap();
    let conn = match catalogue.as_ref() {
        Some(c) => c,
        None => {
            eprintln!("Catalogue not initialized");
            return 0;
        }
    };

    let insert_sql = r#"
        INSERT OR IGNORE INTO images (
            file_path, file_size, file_name, file_extension,
            created_timestamp, modified_timestamp,
            camera_make, camera_model, lens_model,
            focal_length, aperture, shutter_speed, iso,
            capture_datetime,
            pixel_width, pixel_height, color_space, bit_depth,
            gps_latitude, gps_longitude, gps_altitude,
            copyright, creator, description,
            rating, flag, color_label
        ) VALUES (
            ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10,
            ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18,
            ?19, ?20, ?21, ?22, ?23, ?24, ?25, ?26, ?27
        )
    "#;

    let mut inserted_count = 0u32;

    for record in metadata {
        let result = conn.execute(
            insert_sql,
            params![
                record.file_path,
                record.file_size as i64,
                record.file_name,
                record.file_extension,
                record.created_timestamp,
                record.modified_timestamp,
                record.camera_make,
                record.camera_model,
                record.lens_model,
                record.focal_length,
                record.aperture,
                record.shutter_speed,
                record.iso.map(|v| v as i64),
                record.capture_datetime,
                record.pixel_width.map(|v| v as i64),
                record.pixel_height.map(|v| v as i64),
                record.color_space,
                record.bit_depth.map(|v| v as i64),
                record.gps_latitude,
                record.gps_longitude,
                record.gps_altitude,
                record.copyright,
                record.creator,
                record.description,
                record.rating.map(|v| v as i64),
                record.flag,
                record.color_label,
            ],
        );

        match result {
            Ok(changed) => inserted_count += changed as u32,
            Err(e) => eprintln!("Failed to insert record {}: {}", record.file_path, e),
        }
    }

    inserted_count
}

/// Get the total count of images in the catalogue
pub async fn get_image_count() -> u64 {
    let catalogue = CATALOGUE.lock().unwrap();
    let conn = match catalogue.as_ref() {
        Some(c) => c,
        None => {
            eprintln!("Catalogue not initialized");
            return 0;
        }
    };

    let count_result: Result<i64, _> = conn.query_row(
        "SELECT COUNT(*) FROM images",
        [],
        |row| row.get(0),
    );

    match count_result {
        Ok(count) => count as u64,
        Err(e) => {
            eprintln!("Failed to query image count: {}", e);
            0
        }
    }
}
